### ISSUE TITLE
REQUEST - Flag to not pause after decrypted ISO created

### ISSUE THREAD

**Issue by goldenegg** [Redrrx/ps3dec#1]
I would like to request a new flag that would allow the tool to be automated for bulk conversion. Right now, it stops after creating the decrypted ISO and waits for a key to be pressed. It would be helpful to have an option that will not have this pause.

**Comment by Redrrx** [comment]
@goldenegg I have added it in the 0.2.0 preview, please test it and let me know if anything.

its a flag which is --skip, but it does not work in the drag and drop mode for now, it should work for your batching use case.

https://github.com/Redrrx/ps3dec/releases/tag/0.2.0

**Comment by goldenegg** [comment]
Thank you! It appears to work as expected.
